FROM node:22

# Définir le répertoire de travail dans le conteneur
WORKDIR /app

# Copier le package.json et le package-lock.json
COPY ./jetriemesdechets/package*.json ./

# Installer les dépendances
RUN npm install

# Copier le reste de l'application
COPY ./jetriemesdechets ./

# Exposer le port sur lequel l'application Next.js sera exécutée
EXPOSE 3000

# Démarrer l'application Next.js en mode développement
CMD ["npm", "run", "dev"]
