version: '3.7'

services:
  postgres:
    image: postgres:latest
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - '5432:5432'

  backend:
    build:
      context: ./backend
      dockerfile: ./dockerfile
    volumes:
      - ./backend:/app
    ports:
      - '3001:3001'
    depends_on:
      - postgres
    environment:
      DB_USER: ${POSTGRES_USER}
      DB_PASSWORD: ${POSTGRES_PASSWORD}
      DB_HOST: postgres
      DB_PORT: 5432
      DB_NAME: ${POSTGRES_DB}

  frontend:
    build:
      context: ./frontend
      dockerfile: ./dockerfile
    ports:
      - '3000:3000'
    depends_on:
      - backend

volumes:
  postgres_data:
