FROM node:22

# Définir le répertoire de travail dans le conteneur
WORKDIR /app

# Copier le package.json et le package-lock.json dans le répertoire de travail du conteneur
COPY package*.json ./

# Configurer npm pour ignorer les vérifications SSL strictes
RUN npm config set strict-ssl false

# Installer les dépendances
RUN npm install

# Copier le reste de l'application
COPY . .

# Installer TypeScript globalement
RUN npm install -g typescript

# Compiler le code TypeScript en JavaScript
RUN npm run build

# Exposer le port sur lequel le backend est exécuté (exemple: 3001)
EXPOSE 3001

# Démarrer le serveur
CMD ["npm", "start"]
